version: '3.4'

services:
  web:
    image: Limbus_wordle_backend:latest
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    environment:
      - IdentityJSONFile=${IdentityJSONFile}
      - DailyIdentityJSONFile=${DailyIdentityJSONFile}
      - IdentityImgFilePath=${IdentityImgFilePath}
      - CookiePass=${CookiePass}
      - CLOUDINARY_URL=${CLOUDINARY_URL}
      - FRONTEND_URL=${FRONTEND_URL}
      - LISTEN_ON=${LISTEN_ON}
